# SCRIPT TO ADD BATCH ORDERS IMPORT IN OPENCART v1.5.x
# WWW.GODROPSHIPPING.COM
# WuChang

# THIS UPGRADE ONLY APPLIES TO PREVIOUS 1.5.x VERSIONS. DO NOT RUN THIS SCRIPT IF UPGRADING FROM v1.4.x 

# DO NOT RUN THIS ENTIRE FILE MANUALLY THROUGH PHPMYADMIN OR OTHER MYSQL DB TOOL
# THIS FILE IS GENERATED FOR USE WITH THE UPGRADE.PHP SCRIPT LOCATED IN THE INSTALL FOLDER
# THE UPGRADE.PHP SCRIPT IS DESIGNED TO VERIFY THE TABLES BEFORE EXECUTING WHICH PREVENTS ERRORS

# IF YOU NEED TO MANUALLY RUN THEN YOU CAN DO IT BY INDIVIDUAL VERSIONS. EACH SECTION IS LABELED.
# BE SURE YOU CHANGE THE PREFIX "oc_" TO YOUR PREFIX OR REMOVE IT IF NOT USING A PREFIX


#### Version 1.5.1.3, Create

CREATE TABLE IF NOT EXISTS gds_order_group (
    order_group_id int(11) NOT NULL COMMENT '' auto_increment,
    customer_id int(11) NOT NULL DEFAULT 0 COMMENT '',
    customer_group_id int(11) NOT NULL DEFAULT 0 COMMENT '',
    `firstname` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT '',
    `lastname` varchar(32) COLLATE utf8_bin NOT NULL,
    `email` varchar(96) COLLATE utf8_bin NOT NULL,
    `telephone` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT '',
    `fax` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT '',
    PRIMARY KEY (order_group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `gds_order` ADD `order_group_id` int(11) NOT NULL DEFAULT 0 COMMENT '';


#### Version 1.5.1.3, Revert

-- ALTER TABLE `gds_order` DROP `order_group_id`;
-- drop table gds_order_group;
