<?php
// Text
$_['text_information']  = 'Information';
$_['text_service']      = 'Customer Service';
$_['text_extra']        = 'Extras';
$_['text_contact']      = 'Contact Us';
$_['text_return']       = 'Returns';
$_['text_sitemap']      = 'Site Map';
$_['text_manufacturer'] = 'Brands';
$_['text_voucher']      = 'Gift Vouchers';
$_['text_affiliate']    = 'Affiliates';
$_['text_special']      = 'Specials';
$_['text_account']      = 'My Account';
$_['text_order']        = 'Order History';
$_['text_wishlist']     = 'Wish List';
$_['text_newsletter']   = 'Newsletter';
$_['text_powered']      = 'Powered By <a href="http://www.opencart.com">OpenCart</a><br /> %s &copy; %s';
//new
				$_['text_social']  = 'Follow Us On Networking';
				$_['text_service']  = 'Our Services';
				$_['text_category']  = 'Categories';
				$_['text_praesent']  = 'Praesent tempus';
				$_['text_dolor']  = 'Dolor pretium';
				$_['text_commodo']  = 'Commodo lorem';
				$_['text_massan']  = 'Massan placerat';
				$_['text_suspendisse']  = 'Suspendisse est';
				$_['text_dropship']  = 'About Dropship';
				$_['text_handling']  = 'Shipping & Handling';
				$_['text_quotations']  = 'Large Order Quotations';
				$_['text_guarantee']  = 'Lowest Price Guarantee';
				$_['text_drop']  = 'Drop Shipping Program';
				$_['text_tracking']  = 'Tracking Packages';
				$_['text_tax']  = 'Do I have to pay tax?';
				$_['text_store']  = 'Fine Our Store';
				$_['text_about']      = 'About Us';
				$_['text_policies']      = 'Privacy Policies';
				$_['text_support']      = 'Support 1800 - 123 456789';
				$_['text_visit']      = 'Find the store you wish to visit';
				$_['text_powered']      = '&copy; 2012 Supermarket Demo Store. All rights reserved.<br /><a title="Opencart Themes" href="http://www.opencart.com"> Opencart Themes</a> by <a title="Opencart Themes" href="http://www.opencart.com">themes.com</a> ';//new
				$_['text_social']  = 'Follow Us On Networking';
				$_['text_service']  = 'Our Services';
				$_['text_category']  = 'Categories';
				$_['text_praesent']  = 'Praesent tempus';
				$_['text_dolor']  = 'Dolor pretium';
				$_['text_commodo']  = 'Commodo lorem';
				$_['text_massan']  = 'Massan placerat';
				$_['text_suspendisse']  = 'Suspendisse est';
				$_['text_dropship']  = 'About Dropship';
				$_['text_handling']  = 'Shipping & Handling';
				$_['text_quotations']  = 'Large Order Quotations';
				$_['text_guarantee']  = 'Lowest Price Guarantee';
				$_['text_drop']  = 'Drop Shipping Program';
				$_['text_tracking']  = 'Tracking Packages';
				$_['text_tax']  = 'Do I have to pay tax?';
				$_['text_store']  = 'Fine Our Store';
				$_['text_about']      = 'About Us';
				$_['text_policies']      = 'Privacy Policies';
				$_['text_support']      = 'Support 1800 - 123 456789';
				$_['text_visit']      = 'Find the store you wish to visit';
				$_['text_powered']      = '&copy; 2012 Supermarket Demo Store. All rights reserved.<br /><a title="Opencart Themes" href="http://www.opencart.com"> Opencart Themes</a> by <a title="Opencart Themes" href="http://www.opencart.com">themes.com</a> ';
?>